### ISSUE TITLE
实时监测--在平面图上进行区域配置，编辑信息，点击保存按钮之后，页面无变化。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#120]
测试步骤：
1、进行添加区域操作。
2、编辑区域名称，选择添加的设备和底图。
3、点击“保存”按钮。
期望结果：
3、成功添加区域配置。
实际结果：
3、点击“保存”button之后，页面无反应。

点击“保存”之后结果图：
 
![shangchuan](https://user-images.githubusercontent.com/32258990/31533334-44ed0eb6-b024-11e7-8a87-ae04d8393c72.PNG)

**Comment by Candy713** [comment]
Testing in 1.0.17，配置平面图页面的显示与平面图加载的页面叠加，无法进行配置选项的操作
![screenshot](https://user-images.githubusercontent.com/31914132/31598983-0f6cb726-b283-11e7-936a-60b640f2a04a.jpg)

**Comment by Candy713** [comment]
Verify in 1.0.17_3
