### ISSUE TITLE
实时监测--首次切换到平面图，若无区域平面图信息，提示消息不正确。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#122]
测试步骤：
1、进入实时监测页面。
2、点击切换至平面图
期望结果：
能够明确提示用户当前不存在区域平面图，需要进行配置。
实际结果：
实际结果如图所示：

![111](https://user-images.githubusercontent.com/32258990/31535304-3c11c472-b02d-11e7-9573-d082d2e52f4d.PNG)

**Comment by GreatAuk** [comment]
@brucelan2017 这个是因为你们的后台接口在没有数据的情况下返回的是404状态码（这个是你同事在这种情况下截的图 [Img](http://om4os5jmv.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20171013171654.jpg)），被 catch 到了，建议在没有数据的情况下返回 一个空的字符串，我们前台现在就是这样处理的。

**Comment by Candy713** [comment]
Testing in 1.0.17
页面依然显示服务器错误，紧接着出现了404的error
![jmeter](https://user-images.githubusercontent.com/31914132/31599116-94fd0ce2-b283-11e7-92f4-bcff91cb978b.jpg)

**Comment by GreatAuk** [comment]
还是要参照我上面的评论，你们后台响应的404状态码是很致命的错误，我们定义的错误处理机制肯定会catch并提示的，所以还是建议在没有平面图的情况下返回{string: ''},或者我们这边的错误处理直接忽视所有的404这种错误，讨论下二选一

**Comment by Candy713** [comment]
Verify in 1.0.17_3.  没有平面图的初始门店，没有任何提示，显示窗口空白，可接受。
