### ISSUE TITLE
报修管理-历史报修 查看维修单，撤销的维修单上未显示撤销时间。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#125]
测试步骤：
1、进入报修管理页面。
2、点击历史报修，进入历史报修页面。
3、找到已撤销的维修单，点击“点击查看”。

期望结果：
3、报修详情窗口应该显示该维修单撤销的具体时间。

实际结果：
3、报修详情窗口没有显示维修单的撤销时间。

具体结果如图所示：
![default](https://user-images.githubusercontent.com/32258990/31643258-36601ae0-b322-11e7-9d48-dd7a8194f6a2.PNG)

**Comment by Candy713** [comment]
Verify in 1..0.17_3
