### ISSUE TITLE
Login -- 用户名为“na”登录系统时,提示“请输入正确的用户名”。

### ISSUE THREAD

**Issue by xiaowan1983** [RSPluto/Web-UI#129]
![na](https://user-images.githubusercontent.com/32858567/31644912-8a9e4088-b32b-11e7-8ebb-e9e8ade049a1.png)

**Comment by NarakuX** [comment]
用户名有什么限制,
我们目前只做了长度限制最小3个字符

**Comment by xiaowan1983** [comment]
现在我们应该只做字母，数字和非空的限制就行了，不限定字符个数

**Comment by Candy713** [comment]
Verify in 1.0.19_1
