### ISSUE TITLE
实时监测 - 监测点有一些是没有历史数据的，对应的icon应该不显示。

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#134]
接口返回目前没有这个标志，会相应的做update。

期望的就是，如果标志位显示当前监测点没有配置历史数据，那么系统中不显示该监测点的历史数据icon。
![screenshot](https://user-images.githubusercontent.com/31914132/31751285-27271934-b4b7-11e7-8a5c-99ac3aea625a.jpg)

等待接口更新后，修复该issue

**Comment by GreatAuk** [comment]
这个issue后台还会更新接口是吧

**Comment by Candy713** [comment]
对，等待接口更新后，明确了使用哪个返回来判断，再修

**Comment by Candy713** [comment]
接口已经更新，添加字段loggable在 接口GET /api/devices/stores/{siteId}/detail/{deviceId}中

**Comment by Candy713** [comment]
不小心提交comment给close了，重新打开

**Comment by Candy713** [comment]
Veify in 1.0.19-1
