### ISSUE TITLE
报修管理 - 各状态的表单有一些字段需要移除

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#137]
报修管理里，不同状态的查看报修详情，有些不存在的字段不需要显示。
(初步定义如下，请结合开发实现的角度review下，如果有不合理的，或者从编码角度认为不合适的可以提出来，BA讨论下)

待响应:  去掉 “响应时间” “维修时间” “验收时间” “撤销时间” “维修人员”
待处理:  去掉 “维修时间” “验收时间” “撤销时间” 
待验收:  去掉 “验收时间” “撤销时间”
历史报修:
    1. 撤销的维修单：去掉“维修时间“ “验收时间” 和页面最下方的维修提交结果和图片部分
    2. 正常验收关闭的维修单: 去掉“撤销时间”

**Comment by brucelan2017** [comment]
历史报修:
1. 撤销的维修单：去掉“维修时间“ “验收时间” 和页面最下方的维修提交结果和图片部分
2. 正常验收关闭的维修单: 去掉“撤销时间”


已撤销的维修单详情显示错误依然存在

**Comment by Candy713** [comment]
Testing in 1.0.17_4  历史报修里两种表单，没有修改好

**Comment by GreatAuk** [comment]
做了下修改，但不敢保证。因为这个地方逻辑比较乱，又没真实数据，改完后不好测试，所以如果还有错的话希望提供详细的错误情况，把什么情况下出错，错在什么地方说明下，外加截个图

**Comment by Candy713** [comment]
Verify in 1.0.19_1
