### ISSUE TITLE
实时监测 - 进入实时监测页面，loading加载有些慢

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#138]
进入监测页面时，加载有点慢，平均在五秒以上，请检查下数据展示有没有优化的可能。

![screenshot](https://user-images.githubusercontent.com/31914132/31806738-8fea36be-b59c-11e7-8cf4-c4d81cef3a6f.jpg)

**Comment by GreatAuk** [comment]
当获取设备列表的请求发出后，加载动画出现的，当请求得到响应后加载动画立刻会消失，之后才会进行前端的数据绑定（这个几乎是在一瞬间完成的），所以这几秒时间应该是花在了后台的处理上，前端在这一步没有多大的优化空间了。

**Comment by GreatAuk** [comment]
[gif](http://om4os5jmv.bkt.clouddn.com/20171020.gif) 这张gif是我们把网络模拟成 “slow 3G” 的情况下等到的，可以看出加载动画出现后， 网络请求一直处于 pending 状态下，是在等待后台的响应，而一得到响应，动画立刻消失了，而数据也几乎是同时展示了出来

**Comment by Candy713** [comment]
该issue已转提至后台接口做优化，关闭。
