### ISSUE TITLE
实时监测---切换至平面图出错。完成区域配置之后，将所有配置的区域删除。重新切换到平面图，将会一直加载。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#140]
测试步骤：
1、登录系统，进行实时监测页面。
2、切换至平面图并对某一门店完成区域配置。
3、删除该门店下所有的区域配置信息。
4、重新进入实时监测页面。并切换至该门店的平面图。
期望结果：
4、与当该门店下无区域配置时，首次切换至平面图的显示结果相符合，平面图区域为空。

实际结果：
4、平面图区域一直显示“拼命加载中”。
![default](https://user-images.githubusercontent.com/32258990/31807628-ea7faec4-b5a1-11e7-9cbb-460d8b359916.PNG)

**Comment by GreatAuk** [comment]
把 Console 和 Network（/api/file/resource/download/{siteId}） 里面的内容截个图
