### ISSUE TITLE
报警管理 - 缩短“报警描述”列的默认宽度

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#143]
报警管理的list中，显示的“报警描述”那一栏 现在看来有点太宽了，缩短宽度到15个中文汉字的宽度。

**Comment by GreatAuk** [comment]
我缩小了下报警描述这列占的比例。因为是响应式的表格，所以不可能精确控制大小。如果控制到15个汉字的大小的话，在大多数分辨率下应该会比例不平衡
