### ISSUE TITLE
Dashboard - 在页面停留不离开，会报“禁止操作”的error

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#144]
进入dashboard，过一会儿页面出现禁止操作的报错信息。Debug发现有四个请求device的接口在request，但是dashboard应该是没有用到那个的。
![screenshot1](https://user-images.githubusercontent.com/31914132/32130640-cafc2202-bbce-11e7-8b5d-aa7bd033bddd.jpg)

**Comment by xiangzi1226** [comment]
这个错误我们这边没有出现 建议你周一重新测试一下 看看还会不会出现这个错误

**Comment by brucelan2017** [comment]
![qqq](https://user-images.githubusercontent.com/32258990/32211339-0a4a3c66-be4d-11e7-91b0-20f84fbf1bff.PNG)

**Comment by Candy713** [comment]
Verify in 1.0.21
