### ISSUE TITLE
Dashboard - 能耗 - 能耗总量分布统计图，显示不全

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#145]
![screenshot](https://user-images.githubusercontent.com/31914132/32131015-86eb6188-bbd6-11e7-99b9-dcefdd045328.jpg)

**Comment by NarakuX** [comment]
需后台接口数据中 修改日期格式 月份补齐0

**Comment by Candy713** [comment]
Verify in 1.0. 21
