### ISSUE TITLE
报警管理-如果将发生时间显示为两行，即日期一行时间一行，并缩短报警描述的长度，能否一屏显示完整信息，而不需要横向滚动条。

### ISSUE THREAD

**Issue by Rachelwl** [RSPluto/Web-UI#147]
![image](https://user-images.githubusercontent.com/31916661/32205025-d8f3a6c2-be27-11e7-88b7-61705b323e68.png)

**Comment by GreatAuk** [comment]
稍微做了下调整，你看下效果，如果还不行的话就截张全屏的图给我。
表格如果做成响应式的话，在小屏上就很有可能出现滚动条，如果你们不要求响应式的话就，可以把网页主要要适配的分辨率说下。
