### ISSUE TITLE
登录-点击浏览器页面右上方的“×”符号退出页面，再次访问页面，不需要输入账号和密码就可以访问页面。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#148]
测试步骤：
1、用户登录系统。
2、登录成功之后，记住页面地址。点击浏览器右上方的×号退出系统。
3、再次访问该页面。

期望结果：
3、进入登录页面，需要再次输入账号和密码才能登录。

实际结果：
3、可以不用登录直接进入系统，且可以对系统进行操作。

**Comment by Candy713** [comment]
与 issue #151  duplicated, Verify in 1.0.21
