### ISSUE TITLE
报修管理-调整（具体看详情）

### ISSUE THREAD

**Issue by Rachelwl** [RSPluto/Web-UI#150]
![image](https://user-images.githubusercontent.com/31916661/32213853-eec14970-be57-11e7-84d3-9a5c184f2847.png)

1. 将查看调整到左侧。
2.如果报警管理的发生时间改为了两行显示，这边的维修时间也改为两行显示，保持一致。
3.可以隐藏掉门店电话、报修人、维修人员这三个中的一个或者两个或者全部。尽量可以去掉横向滚动条。

**Comment by GreatAuk** [comment]
将查看调整到左侧??? 删除了维修人员和报修人
