### ISSUE TITLE
实时监测 - 历史曲线图中的时间段，取消最多查询31天的限制

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#152]
当前实现开始和结束时间不能大于31天，

期望去掉31天的限制
![screenshot](https://user-images.githubusercontent.com/31914132/32430098-a5aebeba-c308-11e7-818e-8a3e9e88ee9c.jpg)

**Comment by GreatAuk** [comment]
看了下操作日志、报警、报个管理页面都有31天的限制，要把这个限制删除吗？

**Comment by Candy713** [comment]
Sorry, 没有看到更新的comment。。。请将操作日志，报警管理，报修管理的31天限制去掉。
 Testing 1.0.22 ,  历史曲线图 Pass

**Comment by Candy713** [comment]
Verify in 1.0.23
