### ISSUE TITLE
报警管理-时间两行显示的话，最好是日期一行，时间一行。

### ISSUE THREAD

**Issue by Rachelwl** [RSPluto/Web-UI#153]
![image](https://user-images.githubusercontent.com/31916661/32471949-e86ec3fc-c39a-11e7-8865-a43482f5cbcc.png)

**Comment by GreatAuk** [comment]
这个日期就是一个完整的字符串，不可能说年月日一行，时分秒一行，我现在的处理是让这行字符串在任何分辨率下都不换行
