### ISSUE TITLE
实时监测-删除所有配置的区域之后，再点击该门店不会出现提示信息“未配置平面图”。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#156]
测试步骤：
1、登录系统。
2、进入实时监测页面，点击“切换至平面图”。
3、点击某一个门店，会出现提示信息“未配置平面图”。为某一个门店配置区域。
4、删除配置好的区域。
5、点击删除配置区域信息的门店或者点击切换至平面图到删除配置信息的门店。

期望结果：
5、出现提示信息“未配置平面图”。

实际结果：
5、不会出现任何提示信息。

**Comment by GreatAuk** [comment]
做出了相应修改，但我们这边没法测试，不敢保证一定成功。

**Comment by Candy713** [comment]
Verify in 1.0.22
