### ISSUE TITLE
平面图 - 报警为0的设备，在平面图上的 小花icon 显示应该是蓝色

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#160]
![screenshot](https://user-images.githubusercontent.com/31914132/32770186-a8dec204-c959-11e7-8d14-666c40336cf9.jpg)

**Comment by Candy713** [comment]
Testing 1.0.23， 蓝色的小花需要单击后才会变红色

**Comment by GreatAuk** [comment]
这个我改了，所以打了fixed标签，但还没发布给你们。

**Comment by GreatAuk** [comment]
@Candy713 这个我改了，所以打了fixed标签，但还没发布给你们。

**Comment by Candy713** [comment]
Verify in 1.0.24
