### ISSUE TITLE
实时监测 - 平面图 - 详细信息窗口上需要增加设备名称信息

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#168]
![screenshot](https://user-images.githubusercontent.com/31914132/33463697-f85a102c-d679-11e7-93f7-24fb609083ec.jpg)

**Comment by xiaowan1983** [comment]
![168 fixed](https://user-images.githubusercontent.com/32858567/33918058-6bbf33b4-dfec-11e7-80a2-d51186f4639c.png)
