### ISSUE TITLE
实时监测 - 平面图 - 关键点状态图标显示不全

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#169]
需求 c.	关键点图标显示顺序由icon的值决定，从左到右依次是Compressor，Fan和Defrost。报警状态图标（与现在系统中报警图标一致即可）显示在最左边

测试结果： 测试设备中至少有Fan和Defrost的图标，但是平面图上没有显示

![screenshot](https://user-images.githubusercontent.com/31914132/33464610-18bca0b0-d67e-11e7-9cbf-9fde62fa4029.jpg)

**Comment by xiaowan1983** [comment]
![reopen 169](https://user-images.githubusercontent.com/32858567/33920003-9d8e9574-dff6-11e7-8b78-520e5d5b1efc.png)

**Comment by xiaowan1983** [comment]
![reopen 169](https://user-images.githubusercontent.com/32858567/33920296-2b76be92-dff8-11e7-9fa2-9ba695193601.png)

**Comment by xiaowan1983** [comment]
Verified on v1.0.28
