### ISSUE TITLE
实时监测 - 曲线图 - 在界面选择button切换“天”“周”“月”时，系统没有再次发送新的请求

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#170]
测试步骤：
1. 进入曲线图 （默认查询“天”）；
2. 选择“周”；
3. 选择“月”；
4. 选择“天”

期望结果：
2.&3&4 系统会重新触发请求，并且显示周对应的曲线图；

实际结果：
后面三个操作，界面都显示空白，并没有发送进行新的请求

**Comment by NarakuX** [comment]
后三个操作的接口请求和页面,一起截个图吧

**Comment by xiaowan1983** [comment]
请求的起始时间和结束时间不对，反了。
请你们check下

**Comment by GreatAuk** [comment]
@xiaowan1983 了解

**Comment by Candy713** [comment]
Verify in 1.0.29, 切换查询条件可以触发对应request。新的问题会提新的issue。该issue关闭
