### ISSUE TITLE
报警管理_时间格式请与其他页面保持一致

### ISSUE THREAD

**Issue by Rachelwl** [RSPluto/Web-UI#171]
报警管理页面时间格式：
![image](https://user-images.githubusercontent.com/31916661/34025066-cfe20e8c-e188-11e7-89ee-f5e44954bf55.png)

其他页面时间格式：
![image](https://user-images.githubusercontent.com/31916661/34025087-e3ecc430-e188-11e7-8349-c529c9840160.png)

**Comment by NarakuX** [comment]
报警页面的时间是接口中返回的字符串,对字符串类型的时间不做格式转换,只处理时间戳类型的.
![image](https://user-images.githubusercontent.com/20987094/34033115-ec6cec04-e1b3-11e7-8584-7662f6cc4db1.png)
