### ISSUE TITLE
实时监测 - 曲线图 - 横轴的间隔及时间标注请与之前的保持一致

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#177]
不确定是不是换了chats导致的，横轴的时间标识变了。请与之前横轴间隔显示一致。
截图是目前的情况:
![screen](https://user-images.githubusercontent.com/31914132/34512203-c3ae6116-f09b-11e7-8ab6-59f3fbe7e8ea.jpg)

之前的参考:
![screen1](https://user-images.githubusercontent.com/31914132/34512271-300654ae-f09c-11e7-89f0-93cfcd03412b.jpg)

**Comment by GreatAuk** [comment]
做出了相应修改，但是做到和`highchart`一样是不可能的（两者都会根据跨度的范围来决定使用月，星期，日还是小时范围的刻度，但方式还是有区别的）。

**Comment by Candy713** [comment]
Verify in 1.0.30
