### ISSUE TITLE
总览-能耗-纵坐标轴显示数据不正确。

### ISSUE THREAD

**Issue by xiaowan1983** [RSPluto/Web-UI#186]
![1](https://user-images.githubusercontent.com/32858567/35138182-42fdc3d8-fd28-11e7-8350-1c4bd35f9199.png)

**Comment by xiaowan1983** [comment]
After have a discussion, this is local issue, so close this issue.

**Comment by Candy713** [comment]
Open the issue. 请将纵坐标显示的数值进行进位处理，比如300,000，则显示为300K。

**Comment by Candy713** [comment]
Verify in 1.0.34,
