### ISSUE TITLE
Logout - Session或Token过期后，系统未能自动退出

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#28]
**测试步骤:**

1. 登录系统，等待一段长的时间 （比如，大于2小时）
2. 尝试操作系统切换页面

**实际结果:**
2. 系统提示401错误，页面无响应；

**期望结果:**
2. 系统给出对应提示并自动退回到login页面

![screenshot](https://user-images.githubusercontent.com/31914132/30462288-45b7830a-99f7-11e7-92ef-a554861d4937.jpg)

**测试版本** 1.0.4

**Comment by Candy713** [comment]
Testing in 1.0.11
过期后，页面操作时依然返回401messge
期望结果: 页面给出合理的中文提示，并提供退出的操作
![screenshot](https://user-images.githubusercontent.com/31914132/31001812-113cdf76-a519-11e7-8f0d-9bc2a65d4a06.jpg)

**Comment by NarakuX** [comment]
token过期不是应该返回412状态码吗

**Comment by Candy713** [comment]
Token过期不是user expired。Token 过期是auth鉴权后获得的那串Token的有效使用时间，如果无操作，那么过段时间会过期，过期后再调用接口会鉴权失败，这时是需要重新鉴权登录才能访问接口。
稍后我测试一个Token过期的接口响应体。

**Comment by Candy713** [comment]
接口返回依然是401 ![screenshot](https://user-images.githubusercontent.com/31914132/32083764-bf2eb7aa-baf7-11e7-9cda-3748beb970a1.jpg)

**Comment by Candy713** [comment]
Verify in 1.0.22
