### ISSUE TITLE
Dashboard - 用户有一家店，“当月、上月报警总数”和“本月上月日报警数量对比” 有误 

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#32]
测试用户只关联一家门店。

**1.  用户1 所在门店有8月，9月报警**:
接口返回响应体数据:  [用户1.txt](https://github.com/RSPluto/Web-UI/files/1312819/1.txt)
系统截图:
![screenshot 1](https://user-images.githubusercontent.com/31914132/30572689-d7ea1544-9d21-11e7-99e5-c1db1bb70f3c.jpg)

期望结果: 参考实际响应体返回数据，显示正确的图表数据。 当月: 39   上月：23； 折现图同理。

**2.  用户2 所在门店只有9月报警**:
![screenshot](https://user-images.githubusercontent.com/31914132/30572778-608e6cb0-9d22-11e7-9e28-ff3363cc578f.jpg)
期望结果: 上月总数为0， 当月为21， 折线图也应显示为对应的月份和日期

**Comment by NarakuX** [comment]
响应体中日期应该为连续的数据 显示每天的报警数量 如果当日没有报警则total=0 而不是没有这个数据

**Comment by Candy713** [comment]
nigel，确认下是否接口返回要更改成这种的？
显示每天的报警数量 如果当日没有报警则返回total=0 而不是没有这个数据

**Comment by Candy713** [comment]
根据讨论结果，接口不做处理，只返回当天有报警的数目，没有的数据也不返回0。需要前台进行处理这种情况。
因为这种情况在实际中出现的可能性很大，将issue提高优先级为High

**Comment by Candy713** [comment]
Verify in 1.0.10
