### ISSUE TITLE
Dashboard - 报警信息 - “近30天 报警最高VS最低门店对比”表的显示不正确

### ISSUE THREAD

**Issue by jiawang0918** [RSPluto/Web-UI#33]
步骤：
1. 用有门店数为6的用户登录系统；
2. 查看“近30天 报警最高VS最低门店对比”表. 

预期结果：
2. 1. 表的右上角应该有“最高门店”和“最低门店”的颜色标识；
2.2. 表中数据的显示规则是：
a.如果总店数少于或等于5家，那么最高和最低的就都是这几家店数；
b.如果总店数6-9家，则会有重叠的；
c.如果总点数大于等于10，则会显示5个报警最高和5个报警最低门店（用不同的颜色区分最高与最低门店）。

实际结果：
2. 1. 表的右上角没有“最高门店”和“最低门店”的颜色标识；
2.2. 表上显示了所有6家门店的报警数据。（应该按照预期结果的2.2 - b的规则显示）。

截图：
![default](https://user-images.githubusercontent.com/31978052/30584149-74568cb2-9d5b-11e7-9bab-60324dff4013.png)

**Comment by NarakuX** [comment]
少于10家店时显示全部报警门店，大于等于10家店时不同颜色显示最高最低5家店

**Comment by jiawang0918** [comment]
Verified on v1.0.11

**Comment by jiawang0918** [comment]
open，当有几家店的报警数量是一样时，现在的显示是随机的，应该显示哪家店的规则需要澄清。

**Comment by jiawang0918** [comment]
Verified on 2017.10.19, 现在的规则是：
1. 如果用户名下有报警数据的门店数小于等于10，则图中显示所有的门店数；
2. 如果用户名下有报警数据的门店数大于10，则图中显示报警数最高的5家门店和报警数最低的5家门店，且最高门店和最低门店的颜色不同；
3. 如果其中的几家门店的报警数相同，则按照门店的Id由小到大显示。
