### ISSUE TITLE
Login - auth接口的header不需要 Authorization 这个参数

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#38]
![screenshot](https://user-images.githubusercontent.com/31914132/30730702-8eecb096-9f9b-11e7-9600-92d8efa6112e.jpg)

**Comment by NarakuX** [comment]
目前所有网络请求都以统一格式处理，单独处理需要固定url 与#3冲突。当前不影响鉴权，故保持原样

**Comment by Candy713** [comment]
这个Issue跟我们开发沟通了，说是可以fix的，可以move掉这个选项的，请再评估检查下。
另外，如果fix，请给出影响的scope，尤其是测试需要重新覆盖的功能。

**Comment by Candy713** [comment]
Verify in 1.0.20_1, 目前版本实现只留一个auth，之前options的那个拿掉了
