### ISSUE TITLE
实时监测-“开启拖拽”icon选择不太准确

### ISSUE THREAD

**Issue by Rachelwl** [RSPluto/Web-UI#44]
![image](https://user-images.githubusercontent.com/31916661/30790448-7ced3100-a1de-11e7-9927-5255dd0ac0ad.png)

  建议修改为“手型”
  
![image](https://user-images.githubusercontent.com/31916661/30790502-cfd32e88-a1de-11e7-9534-337102d0eced.png)

选择拖拽状态后 鼠标在可拖拽区域样式也是手型
![image](https://user-images.githubusercontent.com/31916661/30790509-dcd5175e-a1de-11e7-9ca5-1b7de6b3eb84.png)

**Comment by NarakuX** [comment]
改为编辑 保存按钮  拖拽状态在移动到设备上显示为十字图标
