### ISSUE TITLE
实时监测 - 修改监测点的值失败

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#58]
![screenshot](https://user-images.githubusercontent.com/31914132/30898085-0a98e39c-a38c-11e7-957e-8c7766e3d5eb.jpg)

**Comment by NarakuX** [comment]
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:9201/api/points/modify/12312?pointValue=On'
pointId参数是在url中体现的

**Comment by Candy713** [comment]
哦，那是我定位错了，这个借口是post吧

**Comment by Candy713** [comment]
Verify in 1.0.10_1
