### ISSUE TITLE
能耗信息 - “近30天 能耗最高VS最低门店对比”图标中的柱状图不显示

### ISSUE THREAD

**Issue by jiawang0918** [RSPluto/Web-UI#61]
如果门店的能耗值相差大，能耗值小的门店的能耗值的柱状图不能显示。

![compare](https://user-images.githubusercontent.com/31978052/30901293-c43ef374-a399-11e7-8bdf-7c664bc6b5e1.png)

**Comment by Candy713** [comment]
Close in 1.0.19_1
这个现象从功能上无法fix，所以As Design 关闭
