### ISSUE TITLE
报修管理- 新增报修单时默认的电话应该是门店电话

### ISSUE THREAD

**Issue by NancChang** [RSPluto/Web-UI#64]
报修管理- 新增报修单时默认的电话应该是门店电话, 而不是登陆用户电话
![default](https://user-images.githubusercontent.com/31914033/30902944-c0664d3c-a39f-11e7-8774-93a9a524aa08.png)
![api](https://user-images.githubusercontent.com/31914033/30902963-caff9a8c-a39f-11e7-9cf8-d033530a21e2.png)

**Comment by NancChang** [comment]
还是显示登陆用户电话而不是门店电话

**Comment by Candy713** [comment]
verify in 1.0.11
