### ISSUE TITLE
地图导览 - 门店没有分配manager时，弹窗显示null不友好

### ISSUE THREAD

**Issue by Candy713** [RSPluto/Web-UI#72]
![screenshot](https://user-images.githubusercontent.com/31914132/30946813-ae93a084-a438-11e7-87f7-e70ec8ec86d2.jpg)

**Comment by Candy713** [comment]
Testing in 1.0.11
还是null，该门店manager返回没有的话，这儿就空白就好了
![screenshot](https://user-images.githubusercontent.com/31914132/30997172-8ff39402-a4f8-11e7-9b51-004d49bdd095.jpg)

**Comment by Candy713** [comment]
点错comment提交的button，重新open

**Comment by Candy713** [comment]
Testing in 1.0.14
还是 没有好，site的manager为null。

**Comment by NarakuX** [comment]
![image](https://user-images.githubusercontent.com/20987094/31475755-36207282-af35-11e7-9ee7-14d9447db6d2.png)
是否后台返回的数据就是null  我们只处理了后台返回数据为空时不显示 清空一下缓存 排除缓存的影响

**Comment by Candy713** [comment]
接口返回是这样的，是null，不是空，你看下
![screenshot](https://user-images.githubusercontent.com/31914132/31480682-c2f02e16-af51-11e7-8c5c-d2979c112f0c.jpg)

**Comment by Candy713** [comment]
Verify in 1.0.15
