### ISSUE TITLE
实时监控 - 历史数据的“开始时间”和“结束时间”的时间格式应该转换成Epoch的毫秒时间格式

### ISSUE THREAD

**Issue by jiawang0918** [RSPluto/Web-UI#84]
步骤：
1.进入实时监控界面；
2.点击某个门店；
3. 点击某个监控点的“历史数据”的图标。

结果：
界面一直处于“加载中”的状态。

截图：
![epoch timestamp](https://user-images.githubusercontent.com/31978052/30955745-48076b28-a467-11e7-904a-387590c23047.png)

**Comment by jiawang0918** [comment]
1. 时间格式已经改成Epoch的毫秒格式，但是界面显示还是空白，不正确；
2. 我看了返回数据是空，但是我们的api接口返回是有值的；
3. 我们的接口返回数据有些延时，可能你们前台要加延时或者判断。

**Comment by Candy713** [comment]
该log窗口还是无法正常显示: 

error:"FAILURE"
message:"Content type 'multipart/form-data;boundary=----WebKitFormBoundaryB30nFMrrBuE2lQPQ' not supported"
shortMessage:null
status:400
timestamp:1507536640640

![screenshot1](https://user-images.githubusercontent.com/31914132/31329492-f185f662-ad0c-11e7-9b18-076bd896d531.jpg)

**Comment by Candy713** [comment]
Testing in 1.0.14.
接口有数据返回，但是没有看到图出来
![screenshot](https://user-images.githubusercontent.com/31914132/31528105-0b290e16-b004-11e7-9406-32d408aca04a.jpg)

**Comment by Candy713** [comment]
Verify in 1.0.16, 该处的能耗图可以正常加载显示，其他的问题会有新的issue来trace。该issue 关闭。
