### ISSUE TITLE
报修管理-报修管理的报修时间和详情页面的报修时间和响应时间都显示错误

### ISSUE THREAD

**Issue by DemiLLiu** [RSPluto/Web-UI#86]
操作步骤：
1.登陆报修管理
2.报修管理页面
3.点击报修页面详情页面
实际结果：
报修管理的报修时间和详情页面的报修时间和响应时间都显示错误
详看截图：
![3](https://user-images.githubusercontent.com/32256376/30957548-2a780f44-a46d-11e7-8654-e1c296311432.png)

**Comment by DemiLLiu** [comment]
时间格式：0-0-0 0:0:0 错误，维修结果：value错误
截图如下：
![6](https://user-images.githubusercontent.com/32256376/31043523-eba2d108-a5ef-11e7-8aa6-c2e580b4b15b.png)

**Comment by Candy713** [comment]
Verify in 1.0.13
