### ISSUE TITLE
报警管理-新增报修维修单，确定提交之后窗口未关闭，可以多次点击“确认提交”进行报修。且会生成多个同样信息不同维修单号的维修单。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#91]
测试步骤：
1、进入报警管理页面
2、点击报警设备栏对应报修设备之后的“报修”
3、填写维修单信息，点击提交。

实际结果：
提交按钮可以多次点击，且每次点击都会生成一个维修单。

期望结果：
点击提交之后，报修窗口关闭

**Comment by Candy713** [comment]
Verify in 1.0.12
