### ISSUE TITLE
报警管理-没有报修权限的用户登录也能在报警设备栏看到“报修”button。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#92]
实际效果如图：
![www](https://user-images.githubusercontent.com/32258990/30998603-70f3ad94-a502-11e7-96af-1c497e7b60ad.PNG)

需求结果：
只有有报修权限的用户登录才能够出现“报修”button。

**Comment by Candy713** [comment]
Duplicate with issue #112  Close
