### ISSUE TITLE
报警管理——按照报警时间/级别、报警类型、报警门店排序之后页面与页面内容不对应。

### ISSUE THREAD

**Issue by brucelan2017** [RSPluto/Web-UI#99]
将页面显示置于最末页，点击排序的三角。页面内容改变但是页面的页码不变。

![paixu](https://user-images.githubusercontent.com/32258990/31003550-e34bcf0a-a522-11e7-9788-5eaf20995119.PNG)

**Comment by Candy713** [comment]
Verify in 1.0.12. 分页后，再排序，系统会默认返回重新排序后的第一页。
